version: 2
jobs:
  run-automated-tests:
    docker:
      - image: qtoggle/espqtoggle-builder
    working_directory: /opt/espqtoggle
    environment:
      - TEST_JWT_ADMIN_EMPTY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJxVG9nZ2xlIiwidXNyIjoiYWRtaW4iLCJvcmkiOiJjb25zdW1lciJ9.H3TvAcQmDhSel5igbz_kfD_hExMfLJeRA5_aDZ1rOEY
      - TEST_JWT_ADMIN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJxVG9nZ2xlIiwidXNyIjoiYWRtaW4iLCJvcmkiOiJjb25zdW1lciJ9.G5sk6HuwGnN78yszwiDqz_CpL86GVXVooIqyVBxD55g
      - TEST_JWT_NORMAL: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJxVG9nZ2xlIiwidXNyIjoibm9ybWFsIiwib3JpIjoiY29uc3VtZXIifQ.NZ47Ds0o6rRLoxmf7BUaMoP02bg-5gbk6iGwz7Is1L4
      - TEST_JWT_VIEWONLY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJxVG9nZ2xlIiwidXNyIjoidmlld29ubHkiLCJvcmkiOiJjb25zdW1lciJ9.w4rypmwbDYtdvoG544-_I7Vcw4n6KaUNNlfH5aUTHaw
      - TEST_JWT_WEBHOOKS: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJxVG9nZ2xlIiwib3JpIjoiZGV2aWNlIn0.rExjwcHPY77Hi5pi0zIDqiL3dK-3BesrH2SDVdRMySE
      - TEST_SSID: testmyesp
      - TEST_PSK: test1234
      - TEST_PASSWORD: test_password
      - TEST_NETWORK_DEVICE_IP: 10.10.10.15
      - TEST_NETWORK_HOST_IP: 10.10.10.1
      - TEST_NETWORK_START_IP: 10.10.10.10
      - TEST_NETWORK_STOP_IP: 10.10.10.20
      - TEST_NETWORK_MASK: 16
      - JOB_TIMEOUT: 900
    steps:
      - checkout
      - run:
          name: Automated Tests
          no_output_timeout: 30m
          command: |
            cd ${CIRCLE_WORKING_DIRECTORY}
            export SRC_DIR="$(pwd)"
            export VERSION="$(/opt/makever.sh)"
    
            /opt/builder.sh
    
            ${SRC_DIR}/test/testmyesp-helper.sh \
              --server-url ${TESTMYESP_SERVER} \
              --credentials ${TESTMYESP_USERNAME}:${TESTMYESP_PASSWORD} \
              --show-serial-log \
              --verbose \
              --timeout ${JOB_TIMEOUT} \
              --flash-image-fill null.bin 0xFC000 0 16384 \
              --flash-image-url esp_init_data_default.bin 0xFC000 https://github.com/espressif/ESP8266_NONOS_SDK/raw/v2.2.1/bin/esp_init_data_default_v08.bin \
              --flash-image-url sysparam.bin 0xFE000 https://github.com/espressif/ESP8266_NONOS_SDK/raw/v2.2.1/bin/blank.bin \
              --flash-image-url boot.bin 0x00000 https://github.com/espressif/ESP8266_NONOS_SDK/raw/v2.2.1/bin/boot_v1.7.bin \
              --flash-image-file user1.bin 0x01000 ${SRC_DIR}/build/user1.bin \
              --flash-image-file user2.bin 0x81000 ${SRC_DIR}/build/user2.bin \
              --flash-image-fill config.bin 0x7C000 0 16384 \
              --test-cases ${SRC_DIR}/test/test-cases/01-wifi/*.json \
              --test-cases ${SRC_DIR}/test/test-cases/02-api/*/*.json \
              --test-cases ${SRC_DIR}/test/test-cases/03-sleep-mode/*.json \
              --test-cases ${SRC_DIR}/test/test-cases/04-setup-mode/*.json \
              --test-cases ${SRC_DIR}/test/test-cases/05-provisioning/*.json \
              --test-cases ${SRC_DIR}/test/test-cases/06-gpiop/*.json \
              --test-cases ${SRC_DIR}/test/test-cases/07-adcp/*.json

workflows:
  version: 2
  test:
    jobs:
      - automated-tests-approval:
          type: approval
      - run-automated-tests:
          context: qtoggle-global
          requires:
            - automated-tests-approval
